//created on: May 4, 2016
package org.acme.insurance.policyquote

//list any import classes here.
import org.acme.insurance.Driver;
import org.acme.insurance.Policy;


//declare any global variables here




rule "SafeAdults"
    ruleflow-group "calculation"
    when
        //conditions
        driver : Driver(age > 24, numberOfAccident < 1, numberOfTickets <= 1)
        policy : Policy( price == null, policyType == "AUTO" )
    then
        //actions
        modify(policy) {setPrice(120)};
        System.out.println("Fired rule "+kcontext.getRule().getName());

end
