package org.acme.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Driver")
public class Driver implements java.io.Serializable
{

   @Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Driver [driverName=");
		builder.append(driverName);
		builder.append(", age=");
		builder.append(age);
		builder.append(", ssn=");
		builder.append(ssn);
		builder.append(", dlNumber=");
		builder.append(dlNumber);
		builder.append(", numberOfAccident=");
		builder.append(numberOfAccidents);
		builder.append(", numberOfTickets=");
		builder.append(numberOfTickets);
		builder.append(", creditScore=");
		builder.append(creditScore);
		builder.append("]");
		return builder.toString();
	}

static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Driver Name")
   private java.lang.String driverName;
   @org.kie.api.definition.type.Label("Age")
   private java.lang.Integer age;
   @org.kie.api.definition.type.Label("SSN")
   private java.lang.String ssn;
   @org.kie.api.definition.type.Label("DL Number")
   private java.lang.String dlNumber;
   @org.kie.api.definition.type.Label("Number of Accident")
   private java.lang.Integer numberOfAccidents;
   @org.kie.api.definition.type.Label("Number of Tickets")
   private java.lang.Integer numberOfTickets;
   @org.kie.api.definition.type.Label("Credit Score")
   private java.lang.Integer creditScore;

   public Driver()
   {
   }

   public java.lang.String getDriverName()
   {
      return this.driverName;
   }

   public void setDriverName(java.lang.String driverName)
   {
      this.driverName = driverName;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.String getSsn()
   {
      return this.ssn;
   }

   public void setSsn(java.lang.String ssn)
   {
      this.ssn = ssn;
   }

   public java.lang.String getDlNumber()
   {
      return this.dlNumber;
   }

   public void setDlNumber(java.lang.String dlNumber)
   {
      this.dlNumber = dlNumber;
   }

   public java.lang.Integer getNumberOfAccidents()
   {
      return this.numberOfAccidents;
   }

   public void setNumberOfAccidents(java.lang.Integer numberOfAccidents)
   {
      this.numberOfAccidents = numberOfAccidents;
   }

   public java.lang.Integer getNumberOfTickets()
   {
      return this.numberOfTickets;
   }

   public void setNumberOfTickets(java.lang.Integer numberOfTickets)
   {
      this.numberOfTickets = numberOfTickets;
   }

   public java.lang.Integer getCreditScore()
   {
      return this.creditScore;
   }

   public void setCreditScore(java.lang.Integer creditScore)
   {
      this.creditScore = creditScore;
   }

   public Driver(java.lang.String driverName, java.lang.Integer age,
         java.lang.String ssn, java.lang.String dlNumber,
         java.lang.Integer numberOfAccident, java.lang.Integer numberOfTickets,
         java.lang.Integer creditScore)
   {
      this.driverName = driverName;
      this.age = age;
      this.ssn = ssn;
      this.dlNumber = dlNumber;
      this.numberOfAccidents = numberOfAccident;
      this.numberOfTickets = numberOfTickets;
      this.creditScore = creditScore;
   }

}